### ISSUE TITLE
plugin throws error message when vite.config.ts/js does not exist

### ISSUE THREAD

**Issue by Roni1993** [danielwaltz/vite-plugin-graphql-codegen#1]
Hey Daniel,

thanks for creating this little tool. It's nice to avoid building weird concurrent processes for multiple watchers.
I've tried to implement this plugin in SvelteKit which has it's Vite config "hidden" inside the `svelte.config.js`.
That causes this plugin to throw an error when it tries to load the vite.config.ts/js:
```
page-svelte@0.0.1 dev
 svelte-kit dev

(node:23438) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use node --trace-warnings ... to show where the warning was created)
 EISDIR: illegal operation on a directory, read
```

this is my svelte.config.js:
```
import adapter from '@sveltejs/adapter-netlify';
import preprocess from 'svelte-preprocess';
import codegen from 'vite-plugin-graphql-codegen';

/** @type {import('@sveltejs/kit').Config} */
const config = {
    // Consult https://github.com/sveltejs/svelte-preprocess
    // for more information about preprocessors
    preprocess: preprocess(),
    svelteOptions: {
        // Same options that you pass to preprocess in svelte.config.js
        preprocess: preprocess(),
    },
    kit: {
        adapter: adapter(),

        // hydrate the <div id="svelte"> element in src/app.html
        target: '#svelte',
        vite: {
            optimizeDeps: {
                exclude: ['@urql/svelte'],
            },
            plugins: [
                codegen.default()
            ],
        }
    }
};

export default config;
```

Do you have any idea what exactly causes this?
If i create a vite.config it works as expected.

**Comment by danielwaltz** [comment]
@Roni1993 Thank you for the kind words! That is an interesting issue to have, could be related to a feature I added recently related to restarting vite when a graphql codegen config file changes. I will investigate this and let you know what I find!

In the meantime, if the problem is indeed caused by a newer version, you could try reverting to an older version of the plugin to see if that helps. [1.1.1](https://github.com/danielwaltz/vite-plugin-graphql-codegen/releases/tag/v1.1.1) was the last release before the vite restart feature so that might still work for you!

**Comment by Roni1993** [comment]
thank for the quick response!
I gave the version 1.1.1 a try and sadly got the same error message.
Any other ideas how i could debug this maybe?

**Comment by danielwaltz** [comment]
I have been considering a debug option in the plugin that you could opt into to have the plugin log things at certain stages - maybe this is as good a time as any to add the feature to help us nail down what's happening here. 🤔

Outside of that, a naive suggestion is try creating a new function in the svelte config file called something like `getCodegenPlugin` that returns the plugin in a try/catch block and see if it will log any uncaught errors. Not sure if that will do anything though to be honest!

**Comment by danielwaltz** [comment]
@Roni1993 I published a new version of the plugin that includes a new debug option. I would suggest updating to the latest version and enabling it by doing `codegen({ debug: true })`. Let me know if you see any output from that!

**Comment by Roni1993** [comment]
i tested the new version and this is the result i got:
```
npm run dev

> page-svelte@0.0.1 dev
> svelte-kit dev

[vite-plugin-graphql-codegen] Plugin initialized with options: { debug: true }
(node:3350) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[vite-plugin-graphql-codegen] Plugin initialized with options: { debug: true }
[vite-plugin-graphql-codegen] Loading codegen context
> EISDIR: illegal operation on a directory, read
```

just to check i ran the normal code generation with the same setup & this works:
```
 npm run gen

> page-svelte@0.0.1 gen
> graphql-codegen

(node:3596) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Parse configuration
  ✔ Generate outputs
```

maybe i'm missing some context here because vite is quite new to me & i'm not sure how exactly svelte-kit is using it

**Comment by Roni1993** [comment]
i was now looking a bit further into it and it seems like the context might not be the same as if this plugin is executed with vite in a direct fashion?

i changed a few lines in the minified code of the downloaded packge just to hack arround a bit and by coincidence i was able to find that if i pass the path directly to my codegen.yaml it works perfectly fine.
```
                log('Loading codegen context ' +_config.root );
                _context.next = 3;
                return cli.loadContext(_config.root + "/codegen.yml");
```

i created a very naive PR for this change but feel free to ignore it/improve on it in any way you please. I've never worked on libraries before so i might be missing obvious issues

**Comment by danielwaltz** [comment]
Good find! I'll look over your PR and see if there are any tweaks to be made!

**Comment by Roni1993** [comment]
The new version with the flag works as expected. Thanks a lot!
