### ISSUE TITLE
How do I pass extra args to the codegen command?

### ISSUE THREAD

**Issue by mdoesburg** [danielwaltz/vite-plugin-graphql-codegen#14]
I am facing an issue where I need to be able to pass extra arguments to the `graphql-codegen` command that can't be configured through the config file.

Is there a way to pass args to the command used to generate the schema?

For example I have to be able to add this to the command:

```
graphql-codegen --require dotenv/config
```

Even though you can set the `require` key, in codegen config (`require: ['dotenv/config']`), this wont work because the `.env` variables have to be loaded before the config gets loaded. Therefore the suggested solution is to pass additional args to the command. See [docs](https://the-guild.dev/graphql/codegen/docs/config-reference/require-field#dotenv-integration).

Would be nice to be able to do this somehow while still being able to use this nice Vite plugin.

**Comment by rbozan** [comment]
So how did you solve this?

**Comment by mdoesburg** [comment]
> So how did you solve this?

I can’t recall the exact issue we ran into, but here’s our current config and script setup. I hope it helps!

**package.json**

```json
"scripts": {
    "codegen": "graphql-codegen --require dotenv/config --config codegen.ts dotenv_config_path=.env.development"
}
```

**codegen.ts**

```ts
import { CodegenConfig } from '@graphql-codegen/cli';

const { VITE_API_URL, INTROSPECTION_TOKEN } = process.env;

const headers = {
    headers: {
        Authorization: `Bearer ${INTROSPECTION_TOKEN}`,
    },
};

const config: CodegenConfig = {
    schema: [
        { [`${VITE_API_URL}/graphql`]: headers },
        { [`${VITE_API_URL}/graphql1`]: headers },
        { [`${VITE_API_URL}/graphql2`]: headers },
    ],
    documents: ['!src/**/*.vue', 'src/**/*.ts', '!src/graphql/**/*'],
    generates: {
        './src/graphql/': {
            preset: 'client',
            presetConfig: {
                fragmentMasking: false,
            },
            plugins: [],
        },
    },
    config: {
        useTypeImports: true,
        avoidOptionals: {
            field: true,
            inputValue: false,
            object: false,
            defaultValue: true,
        },
        namingConvention: {
            enumValues: 'change-case-all#upperCase',
        },
        scalars: {
            DateTime: 'string',
            Decimal: 'string',
            TZDateTime: 'string',
            JSONString: 'string',
        },
    },
};

export default config;
```

**Comment by carloschneider** [comment]
@rbozan here is my solution:

```ts
import codegen from 'vite-plugin-graphql-codegen'

export default defineConfig(({ mode }) => {
  return {
    plugins: [
      codegen({
        configFilePathOverride: `src/graphql/codegen-${mode}.ts`,
      }),
    ],
  }
})
```

`mode` is the prop with the env that Vite makes available ("development", "test", etc). So basically I created different codegen files for each env.

- src/graphql/codegen-development.ts
- src/graphql/codegen-test.ts

And I created a codegen "base" to import in the above files:

- src/graphql/codegen.ts
