### ISSUE TITLE
Watcher not working with documents

### ISSUE THREAD

**Issue by jaulz** [danielwaltz/vite-plugin-graphql-codegen#16]
This plugin looks really promising but I don't know why it doesn't work for me... my config looks like this:
```typescript
import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: './storage/app/lighthouse-schema.graphql',
  documents: [
    // './resources/scripts/**/*.vue',
    './graphql/**/*.queries.graphql',
  ],
  generates: {
    './resources/scripts/graphql/': {
      preset: 'client',
    },
  },
  verbose: true,
  errorsOnly: true,
}

export default config
````

Running `yarn graphql-codegen --watch` works without issues but this plugin doesn't seem to do anything except on first start.

This is how I load the plugin:
````typescript
      codegen({
        enableWatcher: true,
        matchOnSchemas: true,
        debug: true,
      }),
````

Is there anything I missed?

**Comment by jaulz** [comment]
I checked the code and I think the code does not actually consider any of the documents defined in codegen config but instead it just takes the files which Vite handles?

**Comment by danielwaltz** [comment]
Hmm, I think you're right about that assessment. I'm not sure why that directory wouldn't be picked up by the Vite dev server, but I think that is a hard requirement for this plugin to function. Otherwise you may be better off using the watcher provided by the graphql codegen cli directly!

**Comment by jaulz** [comment]
Yeah, too bad it doesn't work this way but then I will fallback to the default CLI. Thanks anyway!
