### ISSUE TITLE
Rebuild doesn't trigger on schema file change

### ISSUE THREAD

**Issue by hahn-kev** [danielwaltz/vite-plugin-graphql-codegen#21]
I've got a 3rd party updating the schema file automatically, and I'd like to have the plugin notice that and run the build again. Here's my config that's passed into the `codegen` function:
```ts
import type {Options} from 'vite-plugin-graphql-codegen';
//https://the-guild.dev/graphql/codegen/docs/guides/svelte
//config passed into vite instead of via codegen file, works the same though
import type {TypeScriptPluginConfig} from '@graphql-codegen/typescript/typings/config';

const generationConfig: TypeScriptPluginConfig = {
  useTypeImports: true,
  skipTypename: true,
  strictScalars: true,
  avoidOptionals: true,
  scalars: {
    /* eslint-disable @typescript-eslint/naming-convention */
    'numeric': 'number',
    'timestamp': 'string | Date',
    'timestamptz': 'string | Date',
    'jsonb': 'unknown',
    'uuid': 'string',
    'UUID': 'string',
    'DateTime': 'string | Date'
    /* eslint-enable @typescript-eslint/naming-convention */
  }
};
export const gqlOptions: Options = {
  matchOnSchemas: true,
  config: {
    schema: 'schema.graphql',
    documents: ['src/**/*.{ts,graphql}', '!src/lib/gql/generated/**/*'],
    ignoreNoDocuments: true, // for better experience with the watcher
    // verbose: true,
    generates: {
      './src/lib/gql/generated/': {
        preset: 'client',
        config: generationConfig,
        plugins: []
      }
    }
  }
};
```

is there something that I'm missing that's preventing it from watching `schema.graphql`?

Thank you, love the plugin.

**Comment by danielwaltz** [comment]
I think I figured it out! The check that occurs when matching on schemas was using a relative path for the schema file resolved from codegen, and an absolute path for the file passed from vite.

I updated the logic to check if the resolved schema path appears inside the vite file path instead, which in my local tests appeared to resolve the issue.

Let me know if it's still happening or if you run into any issues and I'd be happy to continue looking into it!

**Comment by hahn-kev** [comment]
Thanks that was quick. Unfortunately it looks like it didn't solve it for me. Here's my debug logs.
```
VITE PLUGIN GRAPHQL CODEGEN   Plugin initialized with options: {
  debug: true,
  config: {
    debug: true,
    schema: 'schema.graphql',
    documents: [ 'src/**/*.{ts,graphql}', '!src/lib/gql/generated/**/*' ],
    ignoreNoDocuments: true,
    generates: { './src/lib/gql/generated/': [Object] }
  }
} 
VITE PLUGIN GRAPHQL CODEGEN   Manual config passed, creating codegen context 
VITE PLUGIN GRAPHQL CODEGEN   Loading codegen context successful 

√ Parse Configuration
‼ Generate outputs
  > Generate to ./src/lib/gql/generated/
    √ Load GraphQL schemas
    √ Load GraphQL documents
    × Unknown scalar type json. Please override it using the "scalars" configuration field!
Running lifecycle hook "afterStart" scripts...
[CLI] Loading Schemas
[CLI] Loading Documents
[CLI] Generating output
VITE PLUGIN GRAPHQL CODEGEN   Generation failed on start 

  VITE v4.3.8  ready in 2469 ms

  ➜  Local:   http://localhost:3000/
  ➜  press h to show help
VITE PLUGIN GRAPHQL CODEGEN   File changed: C:\dev\LexBox\frontend\schema.graphql 
VITE PLUGIN GRAPHQL CODEGEN   Document check successful in file watcher 
```

What I was doing to test this was just edit `schema.graphql` by commenting out `scalar json`, if I start vite it'll try to generate and then fail because it doesn't know how to define scalar, that's what you see when it failed to run. Then I comment out that line and the 2 lines at the end show up saying that it noticed the change, but it doesn't actually trigger a rebuild of the generator.

**Comment by danielwaltz** [comment]
Dang, I bet I know why too. Others have had issues with the flow of file checking that it starts with documents then moves on to schemas... I think it's finally time to refactor so that it runs both checks at the same time. Will use this issue to track that!

**Comment by danielwaltz** [comment]
@hahn-kev Ok, hopefully that did it! Also looking at the debug output above, I don't see the `matchOnSchemas` config option enabled in the `Plugin initialized with options` line. I would also double check that that is enabled!

**Comment by hahn-kev** [comment]
Thanks the `matchOnSchemas` fixed it!
