### ISSUE TITLE
Add support for Vite 5 and Rollup 4

### ISSUE THREAD

**Issue by Soviut** [danielwaltz/vite-plugin-graphql-codegen#28]
I've updated to Vite 5 but the plugin still has a dependency on Vite 4.

It would be great to have the dependency bumped to Vite 5.

**Comment by danielwaltz** [comment]
Strange that you are experiencing this, theoretically the plugin has already been updated to support Vite 5 as long as that is the version being used in your project. I'm going to try releasing a version that just updates deps and the lockfile and we'll see if maybe that will help!
