### ISSUE TITLE
Watch doesn't update on schema change

### ISSUE THREAD

**Issue by andrew-w-ross** [danielwaltz/vite-plugin-graphql-codegen#7]
# Description

Watch mode only seems to look for changes in the document.  I've created [this repo ](https://github.com/andrew-w-ross/vite-plugin-graphql-codegen-default-issue/tree/watch-issue) to recreate the issue. Make sure you're in the watch-issue branch and run dev. Changes to a document, [App.tsx](https://github.com/andrew-w-ross/vite-plugin-graphql-codegen-default-issue/blob/45d54b89815ca03e2bb4b5b69a8572f0c35038b9/src/App.tsx)  for example work fine. But changes to the [schema](https://github.com/andrew-w-ross/vite-plugin-graphql-codegen-default-issue/blob/45d54b89815ca03e2bb4b5b69a8572f0c35038b9/src/schema.ts) don't.

Looking at the plugin code it seems like [this function](https://github.com/danielwaltz/vite-plugin-graphql-codegen/blob/main/src/utils/isGraphQLDocument.ts#L5) just needs to be updated to take schema into account. I opened up a pr #8 to fix this if you like.

**Comment by danielwaltz** [comment]
Sweet, I never even considered the possibility that the schema might coexist in the same place as the UI and documents, but I can see good reasons for that being the case in some instances. Good idea and good solution!

**Comment by andrew-w-ross** [comment]
@danielwaltz I'm actually experimenting using `vite` as my until build chain for both server and client side code. There is a project called `vite-node` that `vitest` uses.
